name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        volumes:
          - /var/lib/mysql

    steps:
      # Vérifie le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 src/

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create .env file for tests
        run: |
          echo "APP_ENV=dev" > Tests/.env
          echo "DB_HOST=127.0.0.1" >> Tests/.env
          echo "DB_NAME=db_test" >> Tests/.env
          echo "DB_USER=root" >> Tests/.env
          echo "DB_PASSWORD=root" >> Tests/.env

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit --configuration phpunit.xml --testdox
